### ISSUE TITLE
audio is messed up on the videos..

### ISSUE THREAD

**Issue by ovladuk** [freyta/WWE-Network-Downloader#2]
there is audio for about 5 second then it cuts out.. same for all videos.

**Comment by freyta** [comment]
What command are you running and what version of ffmpeg do you have installed? what is the file name and what file are you trying to download?

**Comment by ovladuk** [comment]
the command was "python3 main.py -t https://watch.wwe.com/episode/SmackDown-3641"

downloaded all videos from the 1999 smackdown page but all the videos have messed up audio.

**Comment by freyta** [comment]
What's the ffmpeg output?
Upgrade your version of ffmpeg, older ones put the audio out of sync
