### ISSUE TITLE
Error when using main.py

### ISSUE THREAD

**Issue by bigbossman22** [freyta/WWE-Network-Downloader#3]
Trying to figure out how to get this working and I am greeted with this error.

`python3 main.py -t https://watch.wwe.com/episode/Raw-7157
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import wwe
  File "/home/owner/Documents/git/WWE-Network-Downloader/wwe.py", line 6, in <module>
    import arrow, datetime
ModuleNotFoundError: No module named 'arrow'
`

**Comment by freyta** [comment]
Hey mate,

You'll need to run `pip3 install --user -r requirements.txt` to install the missing module(s). Try that and let me know

**Comment by bigbossman22** [comment]
Thank you! After installing the missing modules everything went smoothly. I love that you made it output with correct file names. Am I able to download entire year/season at once?

**Comment by ctrlaltd1337ed** [comment]
> Am I able to download entire year/season at once?

I would also love to be able to do something like this. LetMeAtIt supposedly provides that functionality, but I much prefer what you've put together here, not to mention it's free.

**Comment by freyta** [comment]
That's pretty easy, I just use another script to call the main script/program. Something like this works fine:

```
# Import the needed files.
import requests
import os
# Link to the season we want to download. In this case it is WWE Raw 2009
link = requests.get('https://cdn.watch.wwe.com/api/filter/episodes?showIds=1007&year=2009&page_size=53').json()

# For each of the links in the above json file get the watch URL and send it to the main Python script/program.
for i in link['items']:
    os.system("python3 main.py -s -e -c -t {}".format(i['watchPath']))
```

Paging @ctrlaltd1337ed @bigbossman22

**Comment by bigbossman22** [comment]
Bro, you are the man!
