### ISSUE TITLE
Name of the catalog is invalid

### ISSUE THREAD

**Issue by crafciak31** [freyta/WWE-Network-Downloader#5]
Hello

My downloads fail with the following message
c:\temp\WWE-Network-Downloader-master>python main.py -q 3 -t https://watch.wwe.c
om/program/CM-Punk-Best-in-the-World-12316
Succesfully logged in
Got the video information
aac files finished downloading
ts files finished downloading

Starting to wrtie the metadata file
Finished writing the metadata title

Writing stream title
Finished writing stream title

Traceback (most recent call last):
  File "main.py", line 175, in <module>
    os.makedirs(CONSTANTS.OUTPUT_FOLDER + "/" + series_info[0])
  File "C:\Users\crafciak31\AppData\Local\Programs\Python\Python38\lib\os.py", l
ine 223, in makedirs
    mkdir(name, mode)
NotADirectoryError: [WinError 267] Nazwa katalogu jest nieprawidłowa (the name of the catalog is invalid): 'output/WWE CM Punk: Best in the World'

**Comment by freyta** [comment]
Hey mate.

The issue is because of illegal Windows filenames. Certain characters aren't allowed to be used, I'll update the code shortly.
